# Generated by Django 5.2.7 on 2025-10-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disaster_images/'),
        ),
        migrations.AddField(
            model_name='safezone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='safezone_images/'),
        ),
    ]
